apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-requirements
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: osssecure
  source:
    path: src/app-configs/system-requirements/
    repoURL: https://github.com/todaywasawesome/osssecure/
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: osssecure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=false
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
    retry:
      limit: 10
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
