apiVersion: externaldata.gatekeeper.sh/v1alpha1
kind: Provider
metadata:
  name: cosign-gatekeeper-provider
spec:
  url: http://cosign-gatekeeper-provider.cosign-gatekeeper-provider:8090/validate
  timeout: 30
  insecureTLSSkipVerify: true
