apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:
- osssecure.yaml

patchesStrategicMerge:
- |-
  apiVersion: argoproj.io/v1alpha1
  kind: Rollout
  metadata:
    name: simple-rollout
  spec:
    template:
      spec:
        containers:
        - name: webserver-simple
          image: todaywasawesome/colors:v1.0.1-secure #Available releases are blue, purple, yellow, v0.0.1-test (signed), v1.0.1-secure (signed)
