apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kyverno
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://kyverno.github.io/kyverno/'
    targetRevision: v2.5.3
    chart: kyverno
    helm:
      parameters:
        - name: replicaCount
          value: '1'
  project: osssecure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
