apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opa-cosign-provider
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: osssecure
  source:
    path: src/manifests/policy-cosign-provider/osssecure/
    repoURL: https://github.com/todaywasawesome/osssecure/
    targetRevision: HEAD
  destination:
    namespace: cosign-gatekeeper-provider
    server: https://kubernetes.default.svc
  project: osssecure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=false
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
    retry:
      limit: 10
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
