apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-reject-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: secure
    server: 'https://kubernetes.default.svc'
  source:
    path: src/manifests/demo-reject-app/osssecure/
    repoURL: https://github.com/todaywasawesome/osssecure/
    targetRevision: HEAD
  project: osssecure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=false
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
